package com.alazzi.grocery;
import android.app.AlertDialog;import android.os.Bundle;import android.view.View;import android.widget.*;import java.util.*;
public class MessagesActivity extends androidx.appcompat.app.AppCompatActivity{
 private Repository repo;private LinearLayout list;
 @Override protected void onCreate(Bundle b){super.onCreate(b);repo=new Repository(this);build();}
 private void build(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.setBackgroundColor(Ui.BG);r.addView(Ui.titleBar(this,"الرسائل وواتساب",v->finish(),v->{}),new LinearLayout.LayoutParams(-1,64));r.addView(Ui.button(this,"＋ رسالة جديدة",v->form()),new LinearLayout.LayoutParams(-1,54));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView s=new ScrollView(this);s.addView(list);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);load();}
 private void load(){list.removeAllViews();for(Map<String,Object>x:repo.rows("SELECT id,party_name,phone,message,kind,created_at FROM messages ORDER BY id DESC")){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,String.valueOf(x.get("party_name")),17,true,Ui.TEXT));c.addView(Ui.text(this,String.valueOf(x.get("message")),14,false,Ui.TEXT));c.addView(Ui.text(this,String.valueOf(x.get("phone"))+" | "+x.get("created_at"),11,false,Ui.MUTED));c.addView(Ui.button(this,"واتساب",v->whatsapp(String.valueOf(x.get("phone")),String.valueOf(x.get("message")))),new LinearLayout.LayoutParams(-1,46));list.addView(c,new LinearLayout.LayoutParams(-1,150));}}
 private void form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText n=Ui.edit(this,"اسم المستلم",false),p=Ui.edit(this,"رقم الهاتف",true),m=Ui.edit(this,"نص الرسالة",false);m.setSingleLine(false);m.setMinLines(4);f.addView(n);f.addView(p);f.addView(m);new AlertDialog.Builder(this).setTitle("رسالة جديدة").setView(f).setPositiveButton("حفظ",(d,w)->{android.content.ContentValues v=new android.content.ContentValues();v.put("party_name",n.getText().toString());v.put("phone",p.getText().toString());v.put("message",m.getText().toString());v.put("kind","واتساب");v.put("created_at",Ui.now());AppDatabase.get(this).getWritableDatabase().insert("messages",null,v);load();whatsapp(p.getText().toString(),m.getText().toString());}).setNegativeButton("إلغاء",null).show();}
 private void whatsapp(String phone,String msg){String p=phone.replaceAll("[^0-9]","");if(p.length()==9)p="967"+p;try{android.content.Intent i=new android.content.Intent(android.content.Intent.ACTION_VIEW,android.net.Uri.parse("https://wa.me/"+p+"?text="+android.net.Uri.encode(msg)));startActivity(i);}catch(Exception e){SharePrint.shareText(this,msg);}}
}