package com.alazzi.grocery;

import android.app.AlertDialog;
import android.os.Bundle;
import android.view.View;
import android.widget.*;
import java.util.*;

public class NotesActivity extends androidx.appcompat.app.AppCompatActivity {
    private LinearLayout list;
    @Override protected void onCreate(Bundle b){super.onCreate(b);build();if(getIntent().getBooleanExtra("add",false))showNote();}
    private void build(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Ui.BG);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.addView(Ui.titleBar(this,"الملاحظات",v->finish(),v->{}),new LinearLayout.LayoutParams(-1,64));Button a=Ui.button(this,"＋ ملاحظة جديدة",v->showNote());r.addView(a,new LinearLayout.LayoutParams(-1,54));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView s=new ScrollView(this);s.addView(list);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);load();}
    private void load(){List<Map<String,Object>> rows=AppDatabaseRows.rows(this,"SELECT id,title,body,updated_at FROM notes ORDER BY id DESC");list.removeAllViews();for(Map<String,Object>x:rows){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,String.valueOf(x.get("title")),18,true,Ui.TEXT));c.addView(Ui.text(this,String.valueOf(x.get("body")),14,false,Ui.TEXT));c.addView(Ui.text(this,String.valueOf(x.get("updated_at")),11,false,Ui.MUTED));LinearLayout b=Ui.row(this);b.addView(Ui.button(this,"مشاركة",v->SharePrint.shareText(this,String.valueOf(x.get("title"))+"\n"+String.valueOf(x.get("body")))),new LinearLayout.LayoutParams(0,48,1));b.addView(Ui.button(this,"صورة",v->{android.graphics.Bitmap bm=noteBitmap(String.valueOf(x.get("title")),String.valueOf(x.get("body")));java.io.File f=new java.io.File(getCacheDir(),"note.png");try(java.io.FileOutputStream o=new java.io.FileOutputStream(f)){bm.compress(android.graphics.Bitmap.CompressFormat.PNG,100,o);}catch(Exception e){}SharePrint.shareFile(this,f,"image/png");}),new LinearLayout.LayoutParams(0,48,1));c.addView(b);list.addView(c,new LinearLayout.LayoutParams(-1,180));}}
    private android.graphics.Bitmap noteBitmap(String title,String body){return SharePrint.receipt(this,new HashMap<String,Object>(){{put("business","بقالة العزي للمواد الغذائية");put("type","ملاحظة");put("number",title);put("party",body);put("total",0);put("paid",0);put("remaining",0);}});}
    private void showNote(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText t=Ui.edit(this,"العنوان",false);EditText b=Ui.edit(this,"الملاحظة",false);b.setSingleLine(false);b.setMinLines(5);b.setGravity(android.view.Gravity.TOP|android.view.Gravity.RIGHT);f.addView(t);f.addView(b);new AlertDialog.Builder(this).setTitle("ملاحظة جديدة").setView(f).setPositiveButton("حفظ",(d,w)->{android.content.ContentValues x=new android.content.ContentValues();x.put("title",t.getText().toString());x.put("body",b.getText().toString());x.put("created_at",Ui.now());x.put("updated_at",Ui.now());AppDatabase.get(this).getWritableDatabase().insert("notes",null,x);load();}).setNegativeButton("إلغاء",null).show();}
    static final class AppDatabaseRows{static List<Map<String,Object>> rows(android.content.Context c,String sql){List<Map<String,Object>> o=new ArrayList<>();android.database.Cursor q=AppDatabase.get(c).getReadableDatabase().rawQuery(sql,null);try{String[] cols=q.getColumnNames();while(q.moveToNext()){Map<String,Object>r=new LinkedHashMap<>();for(int i=0;i<cols.length;i++)r.put(cols[i],q.isNull(i)?null:q.getString(i));o.add(r);}}finally{q.close();}return o;}}
}
