package com.alazzi.grocery;

import android.app.AlertDialog;
import android.os.Bundle;
import android.view.View;
import android.widget.*;
import java.util.*;

public class ProductsActivity extends androidx.appcompat.app.AppCompatActivity {
    private Repository repo; private LinearLayout list; private EditText search;
    @Override protected void onCreate(Bundle b){super.onCreate(b);repo=new Repository(this);build();if(getIntent().getBooleanExtra("add",false))showAdd();}
    private void build(){
        LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);r.setBackgroundColor(Ui.BG);r.setPadding(10,8,10,12);
        r.addView(Ui.titleBar(this,"الأصناف والمخزون",v->finish(),v->{}),new LinearLayout.LayoutParams(-1,64));
        LinearLayout tools=Ui.row(this);search=Ui.edit(this,"بحث بالاسم أو الباركود",false);Button add=Ui.button(this,"＋",v->showAdd());tools.addView(search,new LinearLayout.LayoutParams(0,54,1));tools.addView(add,new LinearLayout.LayoutParams(70,54));r.addView(tools);
        list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(list);r.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);
        search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){load(s.toString());}public void afterTextChanged(android.text.Editable e){}});load("");
    }
    private void load(String q){repo.run(()->repo.products(q),new Repository.Callback<List<Map<String,Object>>>(){public void ok(List<Map<String,Object>> rows){list.removeAllViews();for(Map<String,Object> p:rows){LinearLayout c=Ui.card(ProductsActivity.this);c.addView(Ui.text(ProductsActivity.this,String.valueOf(p.get("name")),18,true,Ui.TEXT));c.addView(Ui.text(ProductsActivity.this,"المخزون: "+Ui.number(((Number)p.get("stock")).doubleValue())+" "+p.get("unit"),14,true,Ui.TEXT));c.addView(Ui.text(ProductsActivity.this,"شراء: "+Ui.number(((Number)p.get("buy_price")).doubleValue())+"  |  بيع: "+Ui.number(((Number)p.get("sell_price")).doubleValue()),13,false,Ui.MUTED));if(String.valueOf(p.get("barcode")).length()>0)c.addView(Ui.text(ProductsActivity.this,"باركود: "+p.get("barcode"),12,false,Ui.MUTED));c.setOnClickListener(v->editProduct(p));list.addView(c,new LinearLayout.LayoutParams(-1,112));}}public void fail(Exception e){Toast.makeText(ProductsActivity.this,e.getMessage(),Toast.LENGTH_SHORT).show();}});}
    private void showAdd(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(24,8,24,8);EditText n=Ui.edit(this,"اسم الصنف",false),b=Ui.edit(this,"الباركود",true),u=Ui.edit(this,"وحدة القياس",false),buy=Ui.edit(this,"سعر الشراء",true),sell=Ui.edit(this,"سعر البيع",true),stock=Ui.edit(this,"الرصيد الافتتاحي",true);for(EditText e:new EditText[]{n,b,u,buy,sell,stock})f.addView(e);new AlertDialog.Builder(this).setTitle("إضافة صنف").setView(f).setPositiveButton("حفظ",(d,w)->repo.run(()->repo.addProduct(n.getText().toString(),b.getText().toString(),u.getText().toString(),Ui.num(buy.getText().toString()),Ui.num(sell.getText().toString()),Ui.num(stock.getText().toString()),1),new Repository.Callback<Long>(){public void ok(Long x){load("");Toast.makeText(ProductsActivity.this,"تم حفظ الصنف ✓",Toast.LENGTH_SHORT).show();}public void fail(Exception e){Toast.makeText(ProductsActivity.this,e.getMessage(),Toast.LENGTH_LONG).show();}})).setNegativeButton("إلغاء",null).show();}
    private void editProduct(Map<String,Object> p){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText n=Ui.edit(this,"اسم الصنف",false),sell=Ui.edit(this,"سعر البيع",true),buy=Ui.edit(this,"سعر الشراء",true),stock=Ui.edit(this,"المخزون",true);n.setText(String.valueOf(p.get("name")));sell.setText(String.valueOf(p.get("sell_price")));buy.setText(String.valueOf(p.get("buy_price")));stock.setText(String.valueOf(p.get("stock")));for(EditText e:new EditText[]{n,buy,sell,stock})f.addView(e);new AlertDialog.Builder(this).setTitle("تعديل الصنف").setView(f).setPositiveButton("حفظ",(d,w)->{android.database.sqlite.SQLiteDatabase db=AppDatabase.get(this).getWritableDatabase();android.content.ContentValues v=new android.content.ContentValues();v.put("name",n.getText().toString().trim());v.put("buy_price",Ui.num(buy.getText().toString()));v.put("sell_price",Ui.num(sell.getText().toString()));v.put("stock",Ui.num(stock.getText().toString()));db.update("products",v,"id=?",new String[]{String.valueOf(p.get("id"))});load(search.getText().toString());Toast.makeText(this,"تم التعديل ✓",Toast.LENGTH_SHORT).show();}).setNeutralButton("زيادة/نقص المخزون",(d,w)->stockMove(p)).show();}
    private void stockMove(Map<String,Object> p){EditText q=Ui.edit(this,"كمية الحركة",true);new AlertDialog.Builder(this).setTitle("حركة مخزون").setView(q).setPositiveButton("إضافة",(d,w)->changeStock(p,Ui.num(q.getText().toString()))).setNegativeButton("صرف",(d,w)->changeStock(p,-Ui.num(q.getText().toString()))).show();}
    private void changeStock(Map<String,Object> p,double delta){android.database.sqlite.SQLiteDatabase db=AppDatabase.get(this).getWritableDatabase();db.execSQL("UPDATE products SET stock=stock+? WHERE id=?",new Object[]{delta,p.get("id")});android.content.ContentValues v=new android.content.ContentValues();v.put("product_id",((Number)p.get("id")).longValue());v.put("warehouse_id",1);v.put("qty",delta);v.put("move_type","تسوية مخزون");v.put("details","حركة يدوية");v.put("created_at",Ui.now());db.insert("stock_moves",null,v);load(search.getText().toString());}
}
