package com.alazzi.grocery;
import android.app.AlertDialog;
import android.os.Bundle;
import android.view.View;
import android.widget.*;
import java.util.*;

public class WarehouseActivity extends androidx.appcompat.app.AppCompatActivity {
    private Repository repo; private LinearLayout list;
    @Override protected void onCreate(Bundle b){super.onCreate(b);repo=new Repository(this);build();}
    private void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setBackgroundColor(Ui.BG);
        root.addView(Ui.titleBar(this,"المخازن والتحويل والجرد",v->finish(),v->{}),new LinearLayout.LayoutParams(-1,64));
        LinearLayout tabs=Ui.row(this);
        tabs.addView(Ui.button(this,"المخازن",v->warehouses()),new LinearLayout.LayoutParams(0,52,1));
        tabs.addView(Ui.button(this,"تحويل",v->transfer()),new LinearLayout.LayoutParams(0,52,1));
        tabs.addView(Ui.button(this,"الجرد",v->inventory()),new LinearLayout.LayoutParams(0,52,1));root.addView(tabs);
        list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView s=new ScrollView(this);s.addView(list);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);warehouses();
    }
    private void warehouses(){list.removeAllViews();list.addView(Ui.button(this,"＋ مخزن جديد",v->addWarehouse()),new LinearLayout.LayoutParams(-1,54));for(Map<String,Object>x:repo.rows("SELECT id,name,note FROM warehouses ORDER BY id DESC")){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,String.valueOf(x.get("name")),18,true,Ui.TEXT));c.addView(Ui.text(this,String.valueOf(x.get("note")),13,false,Ui.MUTED));list.addView(c,new LinearLayout.LayoutParams(-1,82));}}
    private void addWarehouse(){EditText n=Ui.edit(this,"اسم المخزن",false);new AlertDialog.Builder(this).setTitle("إضافة مخزن").setView(n).setPositiveButton("حفظ",(d,w)->{android.content.ContentValues v=new android.content.ContentValues();v.put("name",n.getText().toString().trim());AppDatabase.get(this).getWritableDatabase().insertOrThrow("warehouses",null,v);warehouses();}).show();}
    private void transfer(){list.removeAllViews();List<Map<String,Object>> ps=repo.products("");EditText q=Ui.edit(this,"كمية التحويل",true);Spinner p=new Spinner(this),from=new Spinner(this),to=new Spinner(this);ArrayList<String> pn=new ArrayList<>();for(Map<String,Object>x:ps)pn.add(String.valueOf(x.get("name")));p.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,pn));List<Map<String,Object>> ws=repo.rows("SELECT id,name FROM warehouses ORDER BY id");ArrayList<String> wn=new ArrayList<>();for(Map<String,Object>x:ws)wn.add(String.valueOf(x.get("name")));from.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,wn));to.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,wn));list.addView(Ui.text(this,"الصنف",14,true,Ui.TEXT));list.addView(p);list.addView(Ui.text(this,"من",14,true,Ui.TEXT));list.addView(from);list.addView(Ui.text(this,"إلى",14,true,Ui.TEXT));list.addView(to);list.addView(q);list.addView(Ui.button(this,"تنفيذ التحويل",v->{if(ps.isEmpty()||ws.size()<2){Toast.makeText(this,"يلزم صنف ومخزنان على الأقل",Toast.LENGTH_SHORT).show();return;}int pi=p.getSelectedItemPosition(),fi=from.getSelectedItemPosition(),ti=to.getSelectedItemPosition();if(fi==ti){Toast.makeText(this,"اختر مخزنين مختلفين",Toast.LENGTH_SHORT).show();return;}double qty=Ui.num(q.getText().toString());if(qty<=0)return;long pid=((Number)ps.get(pi).get("id")).longValue(),fid=((Number)ws.get(fi).get("id")).longValue(),tid=((Number)ws.get(ti).get("id")).longValue();android.database.sqlite.SQLiteDatabase db=AppDatabase.get(this).getWritableDatabase();db.beginTransaction();try{db.execSQL("INSERT INTO stock_moves(product_id,warehouse_id,qty,move_type,details,created_at) VALUES(?,?,?,?,?,?)",new Object[]{pid,fid,-qty,"تحويل","إلى "+ws.get(ti).get("name"),Ui.now()});db.execSQL("INSERT INTO stock_moves(product_id,warehouse_id,qty,move_type,details,created_at) VALUES(?,?,?,?,?,?)",new Object[]{pid,tid,qty,"تحويل","من "+ws.get(fi).get("name"),Ui.now()});db.setTransactionSuccessful();Toast.makeText(this,"تم التحويل ✓",Toast.LENGTH_SHORT).show();}finally{db.endTransaction();}}),new LinearLayout.LayoutParams(-1,56));}
    private void inventory(){list.removeAllViews();double buy=0,sell=0;for(Map<String,Object>x:repo.products("")){double st=((Number)x.get("stock")).doubleValue();buy+=st*((Number)x.get("buy_price")).doubleValue();sell+=st*((Number)x.get("sell_price")).doubleValue();LinearLayout c=Ui.card(this);c.addView(Ui.text(this,String.valueOf(x.get("name")),16,true,Ui.TEXT));c.addView(Ui.text(this,"الكمية: "+Ui.number(st)+"  | شراء: "+Ui.number(((Number)x.get("buy_price")).doubleValue())+" | بيع: "+Ui.number(((Number)x.get("sell_price")).doubleValue()),13,false,Ui.MUTED));list.addView(c,new LinearLayout.LayoutParams(-1,82));}list.addView(Ui.text(this,"إجمالي الشراء: "+Ui.number(buy)+"  •  إجمالي البيع: "+Ui.number(sell),17,true,Ui.BLUE),new LinearLayout.LayoutParams(-1,60));}
}